baseurl: /TodoCSS
pygments: true
markdown: redcarpet
safe: true

baseurl: /TodoCSS

project-url: https://github.com/operatino/TodoCSS

res-project-author: <a href="http://rhr.me">Robert Haritonov</a>
res-project-author-twitter: <a href="http://twitter.com/operatino_en">@operatino</a>

res-watch-on-github: Checkout project at
res-download-archive: Download archive
res-footer: This site is published through <a href="http://pages.github.com">GitHub Pages</a> based on <a href="http://jekyllrb.com">Jekyll</a>
res-author: Project author

res-navigation-suggested: Suggested projects